/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BuildAgent
    /// </summary>
    [DataContract(Name = "BuildAgent")]
    public partial class BuildAgent : IEquatable<BuildAgent>, IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Unavailable for value: unavailable
            /// </summary>
            [EnumMember(Value = "unavailable")]
            Unavailable = 1,

            /// <summary>
            /// Enum Available for value: available
            /// </summary>
            [EnumMember(Value = "available")]
            Available = 2,

            /// <summary>
            /// Enum Offline for value: offline
            /// </summary>
            [EnumMember(Value = "offline")]
            Offline = 3

        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BuildAgent" /> class.
        /// </summary>
        /// <param name="buildDirectory">buildDirectory.</param>
        /// <param name="controller">controller.</param>
        /// <param name="createdDate">createdDate.</param>
        /// <param name="description">description.</param>
        /// <param name="enabled">enabled.</param>
        /// <param name="id">id.</param>
        /// <param name="messageQueueUrl">messageQueueUrl.</param>
        /// <param name="name">name.</param>
        /// <param name="reservedForBuild">reservedForBuild.</param>
        /// <param name="server">server.</param>
        /// <param name="status">status.</param>
        /// <param name="statusMessage">statusMessage.</param>
        /// <param name="updatedDate">updatedDate.</param>
        /// <param name="uri">uri.</param>
        /// <param name="url">url.</param>
        public BuildAgent(string buildDirectory = default(string), XamlBuildControllerReference controller = default(XamlBuildControllerReference), DateTime createdDate = default(DateTime), string description = default(string), bool enabled = default(bool), int id = default(int), string messageQueueUrl = default(string), string name = default(string), string reservedForBuild = default(string), XamlBuildServerReference server = default(XamlBuildServerReference), StatusEnum? status = default(StatusEnum?), string statusMessage = default(string), DateTime updatedDate = default(DateTime), string uri = default(string), string url = default(string))
        {
            this.BuildDirectory = buildDirectory;
            this.Controller = controller;
            this.CreatedDate = createdDate;
            this.Description = description;
            this.Enabled = enabled;
            this.Id = id;
            this.MessageQueueUrl = messageQueueUrl;
            this.Name = name;
            this.ReservedForBuild = reservedForBuild;
            this.Server = server;
            this.Status = status;
            this.StatusMessage = statusMessage;
            this.UpdatedDate = updatedDate;
            this.Uri = uri;
            this.Url = url;
        }

        /// <summary>
        /// Gets or Sets BuildDirectory
        /// </summary>
        [DataMember(Name = "buildDirectory", EmitDefaultValue = false)]
        public string BuildDirectory { get; set; }

        /// <summary>
        /// Gets or Sets Controller
        /// </summary>
        [DataMember(Name = "controller", EmitDefaultValue = false)]
        public XamlBuildControllerReference Controller { get; set; }

        /// <summary>
        /// Gets or Sets CreatedDate
        /// </summary>
        [DataMember(Name = "createdDate", EmitDefaultValue = false)]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [DataMember(Name = "enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets MessageQueueUrl
        /// </summary>
        [DataMember(Name = "messageQueueUrl", EmitDefaultValue = false)]
        public string MessageQueueUrl { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ReservedForBuild
        /// </summary>
        [DataMember(Name = "reservedForBuild", EmitDefaultValue = false)]
        public string ReservedForBuild { get; set; }

        /// <summary>
        /// Gets or Sets Server
        /// </summary>
        [DataMember(Name = "server", EmitDefaultValue = false)]
        public XamlBuildServerReference Server { get; set; }

        /// <summary>
        /// Gets or Sets StatusMessage
        /// </summary>
        [DataMember(Name = "statusMessage", EmitDefaultValue = false)]
        public string StatusMessage { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedDate
        /// </summary>
        [DataMember(Name = "updatedDate", EmitDefaultValue = false)]
        public DateTime UpdatedDate { get; set; }

        /// <summary>
        /// Gets or Sets Uri
        /// </summary>
        [DataMember(Name = "uri", EmitDefaultValue = false)]
        public string Uri { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BuildAgent {\n");
            sb.Append("  BuildDirectory: ").Append(BuildDirectory).Append("\n");
            sb.Append("  Controller: ").Append(Controller).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MessageQueueUrl: ").Append(MessageQueueUrl).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ReservedForBuild: ").Append(ReservedForBuild).Append("\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusMessage: ").Append(StatusMessage).Append("\n");
            sb.Append("  UpdatedDate: ").Append(UpdatedDate).Append("\n");
            sb.Append("  Uri: ").Append(Uri).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BuildAgent);
        }

        /// <summary>
        /// Returns true if BuildAgent instances are equal
        /// </summary>
        /// <param name="input">Instance of BuildAgent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BuildAgent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BuildDirectory == input.BuildDirectory ||
                    (this.BuildDirectory != null &&
                    this.BuildDirectory.Equals(input.BuildDirectory))
                ) && 
                (
                    this.Controller == input.Controller ||
                    (this.Controller != null &&
                    this.Controller.Equals(input.Controller))
                ) && 
                (
                    this.CreatedDate == input.CreatedDate ||
                    (this.CreatedDate != null &&
                    this.CreatedDate.Equals(input.CreatedDate))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Enabled == input.Enabled ||
                    this.Enabled.Equals(input.Enabled)
                ) && 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.MessageQueueUrl == input.MessageQueueUrl ||
                    (this.MessageQueueUrl != null &&
                    this.MessageQueueUrl.Equals(input.MessageQueueUrl))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ReservedForBuild == input.ReservedForBuild ||
                    (this.ReservedForBuild != null &&
                    this.ReservedForBuild.Equals(input.ReservedForBuild))
                ) && 
                (
                    this.Server == input.Server ||
                    (this.Server != null &&
                    this.Server.Equals(input.Server))
                ) && 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                ) && 
                (
                    this.StatusMessage == input.StatusMessage ||
                    (this.StatusMessage != null &&
                    this.StatusMessage.Equals(input.StatusMessage))
                ) && 
                (
                    this.UpdatedDate == input.UpdatedDate ||
                    (this.UpdatedDate != null &&
                    this.UpdatedDate.Equals(input.UpdatedDate))
                ) && 
                (
                    this.Uri == input.Uri ||
                    (this.Uri != null &&
                    this.Uri.Equals(input.Uri))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BuildDirectory != null)
                {
                    hashCode = (hashCode * 59) + this.BuildDirectory.GetHashCode();
                }
                if (this.Controller != null)
                {
                    hashCode = (hashCode * 59) + this.Controller.GetHashCode();
                }
                if (this.CreatedDate != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedDate.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Enabled.GetHashCode();
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.MessageQueueUrl != null)
                {
                    hashCode = (hashCode * 59) + this.MessageQueueUrl.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.ReservedForBuild != null)
                {
                    hashCode = (hashCode * 59) + this.ReservedForBuild.GetHashCode();
                }
                if (this.Server != null)
                {
                    hashCode = (hashCode * 59) + this.Server.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Status.GetHashCode();
                if (this.StatusMessage != null)
                {
                    hashCode = (hashCode * 59) + this.StatusMessage.GetHashCode();
                }
                if (this.UpdatedDate != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedDate.GetHashCode();
                }
                if (this.Uri != null)
                {
                    hashCode = (hashCode * 59) + this.Uri.GetHashCode();
                }
                if (this.Url != null)
                {
                    hashCode = (hashCode * 59) + this.Url.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
