/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents the ability to build forks of the selected repository.
    /// </summary>
    [DataContract(Name = "Forks")]
    public partial class Forks : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Forks" /> class.
        /// </summary>
        /// <param name="allowSecrets">Indicates whether a build should use secrets when building forks of the selected repository..</param>
        /// <param name="enabled">Indicates whether the trigger should queue builds for forks of the selected repository..</param>
        public Forks(bool allowSecrets = default, bool enabled = default)
        {
            this.AllowSecrets = allowSecrets;
            this.Enabled = enabled;
        }

        /// <summary>
        /// Indicates whether a build should use secrets when building forks of the selected repository.
        /// </summary>
        /// <value>Indicates whether a build should use secrets when building forks of the selected repository.</value>
        [DataMember(Name = "allowSecrets", EmitDefaultValue = true)]
        public bool AllowSecrets { get; set; }

        /// <summary>
        /// Indicates whether the trigger should queue builds for forks of the selected repository.
        /// </summary>
        /// <value>Indicates whether the trigger should queue builds for forks of the selected repository.</value>
        [DataMember(Name = "enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Forks {\n");
            sb.Append("  AllowSecrets: ").Append(AllowSecrets).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
