/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Data representation of an information node associated with a build
    /// </summary>
    [DataContract(Name = "InformationNode")]
    public partial class InformationNode : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InformationNode" /> class.
        /// </summary>
        /// <param name="fields">Fields of the information node.</param>
        /// <param name="lastModifiedBy">Process or person that last modified this node.</param>
        /// <param name="lastModifiedDate">Date this node was last modified.</param>
        /// <param name="nodeId">Node Id of this information node.</param>
        /// <param name="parentId">Id of parent node (xml tree).</param>
        /// <param name="type">The type of the information node.</param>
        public InformationNode(Dictionary<string, string> fields = default, string lastModifiedBy = default, DateTime lastModifiedDate = default, int nodeId = default, int parentId = default, string type = default)
        {
            this.Fields = fields;
            this.LastModifiedBy = lastModifiedBy;
            this.LastModifiedDate = lastModifiedDate;
            this.NodeId = nodeId;
            this.ParentId = parentId;
            this.Type = type;
        }

        /// <summary>
        /// Fields of the information node
        /// </summary>
        /// <value>Fields of the information node</value>
        [DataMember(Name = "fields", EmitDefaultValue = false)]
        public Dictionary<string, string> Fields { get; set; }

        /// <summary>
        /// Process or person that last modified this node
        /// </summary>
        /// <value>Process or person that last modified this node</value>
        [DataMember(Name = "lastModifiedBy", EmitDefaultValue = false)]
        public string LastModifiedBy { get; set; }

        /// <summary>
        /// Date this node was last modified
        /// </summary>
        /// <value>Date this node was last modified</value>
        [DataMember(Name = "lastModifiedDate", EmitDefaultValue = false)]
        public DateTime LastModifiedDate { get; set; }

        /// <summary>
        /// Node Id of this information node
        /// </summary>
        /// <value>Node Id of this information node</value>
        [DataMember(Name = "nodeId", EmitDefaultValue = false)]
        public int NodeId { get; set; }

        /// <summary>
        /// Id of parent node (xml tree)
        /// </summary>
        /// <value>Id of parent node (xml tree)</value>
        [DataMember(Name = "parentId", EmitDefaultValue = false)]
        public int ParentId { get; set; }

        /// <summary>
        /// The type of the information node
        /// </summary>
        /// <value>The type of the information node</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InformationNode {\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  LastModifiedBy: ").Append(LastModifiedBy).Append("\n");
            sb.Append("  LastModifiedDate: ").Append(LastModifiedDate).Append("\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
