/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A valid retention lease prevents automated systems from deleting a pipeline run.
    /// </summary>
    [DataContract(Name = "RetentionLease")]
    public partial class RetentionLease : IEquatable<RetentionLease>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RetentionLease" /> class.
        /// </summary>
        /// <param name="createdOn">When the lease was created..</param>
        /// <param name="definitionId">The pipeline definition of the run..</param>
        /// <param name="leaseId">The unique identifier for this lease..</param>
        /// <param name="ownerId">Non-unique string that identifies the owner of a retention lease..</param>
        /// <param name="runId">The pipeline run protected by this lease..</param>
        /// <param name="validUntil">The last day the lease is considered valid..</param>
        public RetentionLease(DateTime createdOn = default(DateTime), int definitionId = default(int), int leaseId = default(int), string ownerId = default(string), int runId = default(int), DateTime validUntil = default(DateTime))
        {
            this.CreatedOn = createdOn;
            this.DefinitionId = definitionId;
            this.LeaseId = leaseId;
            this.OwnerId = ownerId;
            this.RunId = runId;
            this.ValidUntil = validUntil;
        }

        /// <summary>
        /// When the lease was created.
        /// </summary>
        /// <value>When the lease was created.</value>
        [DataMember(Name = "createdOn", EmitDefaultValue = false)]
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// The pipeline definition of the run.
        /// </summary>
        /// <value>The pipeline definition of the run.</value>
        [DataMember(Name = "definitionId", EmitDefaultValue = false)]
        public int DefinitionId { get; set; }

        /// <summary>
        /// The unique identifier for this lease.
        /// </summary>
        /// <value>The unique identifier for this lease.</value>
        [DataMember(Name = "leaseId", EmitDefaultValue = false)]
        public int LeaseId { get; set; }

        /// <summary>
        /// Non-unique string that identifies the owner of a retention lease.
        /// </summary>
        /// <value>Non-unique string that identifies the owner of a retention lease.</value>
        [DataMember(Name = "ownerId", EmitDefaultValue = false)]
        public string OwnerId { get; set; }

        /// <summary>
        /// The pipeline run protected by this lease.
        /// </summary>
        /// <value>The pipeline run protected by this lease.</value>
        [DataMember(Name = "runId", EmitDefaultValue = false)]
        public int RunId { get; set; }

        /// <summary>
        /// The last day the lease is considered valid.
        /// </summary>
        /// <value>The last day the lease is considered valid.</value>
        [DataMember(Name = "validUntil", EmitDefaultValue = false)]
        public DateTime ValidUntil { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RetentionLease {\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  DefinitionId: ").Append(DefinitionId).Append("\n");
            sb.Append("  LeaseId: ").Append(LeaseId).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  RunId: ").Append(RunId).Append("\n");
            sb.Append("  ValidUntil: ").Append(ValidUntil).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RetentionLease);
        }

        /// <summary>
        /// Returns true if RetentionLease instances are equal
        /// </summary>
        /// <param name="input">Instance of RetentionLease to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RetentionLease input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                this.CreatedOn.Equals(input.CreatedOn) && 
                (
                    this.DefinitionId == input.DefinitionId ||
                    this.DefinitionId.Equals(input.DefinitionId)
                ) && 
                (
                    this.LeaseId == input.LeaseId ||
                    this.LeaseId.Equals(input.LeaseId)
                ) && 
                (
                    this.OwnerId == input.OwnerId ||
                    (this.OwnerId != null &&
                    this.OwnerId.Equals(input.OwnerId))
                ) && 
                (
                    this.RunId == input.RunId ||
                    this.RunId.Equals(input.RunId)
                ) && 
                this.ValidUntil.Equals(input.ValidUntil);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                                    hashCode = (hashCode * 59) + this.CreatedOn.GetHashCode();
                hashCode = (hashCode * 59) + this.DefinitionId.GetHashCode();
                hashCode = (hashCode * 59) + this.LeaseId.GetHashCode();
                if (this.OwnerId != null)
                {
                    hashCode = (hashCode * 59) + this.OwnerId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.RunId.GetHashCode();
                                    hashCode = (hashCode * 59) + this.ValidUntil.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
