/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents a reference to an orchestration plan.
    /// </summary>
    [DataContract(Name = "TaskOrchestrationPlanReference")]
    public partial class TaskOrchestrationPlanReference : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskOrchestrationPlanReference" /> class.
        /// </summary>
        /// <param name="orchestrationType">The type of the plan..</param>
        /// <param name="planId">The ID of the plan..</param>
        public TaskOrchestrationPlanReference(int orchestrationType = default, Guid planId = default)
        {
            this.OrchestrationType = orchestrationType;
            this.PlanId = planId;
        }

        /// <summary>
        /// The type of the plan.
        /// </summary>
        /// <value>The type of the plan.</value>
        [DataMember(Name = "orchestrationType", EmitDefaultValue = false)]
        public int OrchestrationType { get; set; }

        /// <summary>
        /// The ID of the plan.
        /// </summary>
        /// <value>The ID of the plan.</value>
        [DataMember(Name = "planId", EmitDefaultValue = false)]
        public Guid PlanId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskOrchestrationPlanReference {\n");
            sb.Append("  OrchestrationType: ").Append(OrchestrationType).Append("\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
