/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TaskOrchestrationPlanGroupsStartedEvent
    /// </summary>
    [DataContract(Name = "TaskOrchestrationPlanGroupsStartedEvent")]
    public partial class TaskOrchestrationPlanGroupsStartedEvent : IEquatable<TaskOrchestrationPlanGroupsStartedEvent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskOrchestrationPlanGroupsStartedEvent" /> class.
        /// </summary>
        /// <param name="planGroups">planGroups.</param>
        public TaskOrchestrationPlanGroupsStartedEvent(List<TaskOrchestrationPlanGroupReference> planGroups = default(List<TaskOrchestrationPlanGroupReference>))
        {
            this.PlanGroups = planGroups;
        }

        /// <summary>
        /// Gets or Sets PlanGroups
        /// </summary>
        [DataMember(Name = "planGroups", EmitDefaultValue = false)]
        public List<TaskOrchestrationPlanGroupReference> PlanGroups { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskOrchestrationPlanGroupsStartedEvent {\n");
            sb.Append("  PlanGroups: ").Append(PlanGroups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaskOrchestrationPlanGroupsStartedEvent);
        }

        /// <summary>
        /// Returns true if TaskOrchestrationPlanGroupsStartedEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of TaskOrchestrationPlanGroupsStartedEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskOrchestrationPlanGroupsStartedEvent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PlanGroups == input.PlanGroups ||
                    this.PlanGroups != null &&
                    input.PlanGroups != null &&
                    this.PlanGroups.SequenceEqual(input.PlanGroups)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PlanGroups != null)
                {
                    hashCode = (hashCode * 59) + this.PlanGroups.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
