CREATE TABLE [dbo].[SERVER_SERVICE_MAP] (
    [Server_ID]  INT NOT NULL,
    [Service_ID] INT NOT NULL,
    CONSTRAINT [SERVER_SERVICE_MAP_SERVER_Server_ID_fk] FOREIGN KEY ([Server_ID]) REFERENCES [dbo].[SERVER] ([Server_ID]),
    CONSTRAINT [SERVER_SERVICE_MAP_SERVICE_Service_ID_fk] FOREIGN KEY ([Service_ID]) REFERENCES [dbo].[SERVICE] ([Service_ID])
)
WITH (DATA_COMPRESSION = PAGE);



