// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AnalyticsRecoveryTimeApiModel
 */
export interface AnalyticsRecoveryTimeApiModel {
    /**
     * @type {string}
     * @memberof AnalyticsRecoveryTimeApiModel
     */
    ProjectName?: string;
    /**
     * @type {number}
     * @memberof AnalyticsRecoveryTimeApiModel
     */
    MedianRecoveryHours?: number;
    /**
     * @type {number}
     * @memberof AnalyticsRecoveryTimeApiModel
     */
    AvgRecoveryHours?: number;
    /**
     * @type {number}
     * @memberof AnalyticsRecoveryTimeApiModel
     */
    SampleCount?: number;
}
