// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CopyEnvBuildResponseDto
 */
export interface CopyEnvBuildResponseDto {
    /**
     * @type {Array<number>}
     * @memberof CopyEnvBuildResponseDto
     */
    RequestIds?: Array<number> | null;
    /**
     * @type {string}
     * @memberof CopyEnvBuildResponseDto
     */
    Message?: string | null;
    /**
     * @type {boolean}
     * @memberof CopyEnvBuildResponseDto
     */
    Success?: boolean;
}
