// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DaemonApiModel
 */
export interface DaemonApiModel {
  /**
   * @type {number}
   * @memberof DaemonApiModel
   */
  Id?: number;
  /**
   * @type {string}
   * @memberof DaemonApiModel
   */
  Name?: string | null;
  /**
   * @type {string}
   * @memberof DaemonApiModel
   */
  DisplayName?: string | null;
  /**
   * @type {string}
   * @memberof DaemonApiModel
   */
  AccountName?: string | null;
  /**
   * @type {string}
   * @memberof DaemonApiModel
   */
  ServiceType?: string | null;
  /**
   * @type {string}
   * @memberof DaemonApiModel
   */
  ServerName?: string | null;
}
