// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DatabaseAccessPrincipal
 */
export interface DatabaseAccessPrincipal {
    /**
     * @type {string}
     * @memberof DatabaseAccessPrincipal
     */
    Name: string;
    /**
     * @type {string}
     * @memberof DatabaseAccessPrincipal
     */
    Kind: string;
    /**
     * @type {string}
     * @memberof DatabaseAccessPrincipal
     */
    LoginName?: string | null;
    /**
     * @type {string}
     * @memberof DatabaseAccessPrincipal
     */
    DirectoryId?: string | null;
    /**
     * @type {boolean}
     * @memberof DatabaseAccessPrincipal
     */
    Present: boolean;
    /**
     * @type {number}
     * @memberof DatabaseAccessPrincipal
     */
    LegacyUserId?: number | null;
}
