// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DatabaseApiModel
 */
export interface DatabaseApiModel {
    /**
     * @type {Array<string>}
     * @memberof DatabaseApiModel
     */
    EnvironmentNames?: Array<string> | null;
    /**
     * @type {boolean}
     * @memberof DatabaseApiModel
     */
    UserEditable?: boolean;
    /**
     * @type {Array<string>}
     * @memberof DatabaseApiModel
     */
    Name?: string | null;
    /**
     * @type {Array<string>}
     * @memberof DatabaseApiModel
     */
    Tags?: Array<string> | null;
    /**
     * @type {Array<string>}
     * @memberof DatabaseApiModel
     */
    ServerName?: string | null;
    /**
     * @type {Array<string>}
     * @memberof DatabaseApiModel
     */
    AdGroup?: string | null;
    /**
     * @type {number}
     * @memberof DatabaseApiModel
     */
    Id?: number;
    /**
     * @type {Array<string>}
     * @memberof DatabaseApiModel
     */
    ArrayName?: string | null;
}
