// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    DaemonStatusApiModel,
} from './';

/**
 * @export
 * @interface DiscoverDaemonsResult
 */
export interface DiscoverDaemonsResult {
    /**
     * @type {number}
     * @memberof DiscoverDaemonsResult
     */
    MappingsCreated?: number;
    /**
     * @type {number}
     * @memberof DiscoverDaemonsResult
     */
    ServersProcessed?: number;
    /**
     * @type {number}
     * @memberof DiscoverDaemonsResult
     */
    DaemonsDiscovered?: number;
    /**
     * @type {Array<string>}
     * @memberof DiscoverDaemonsResult
     */
    Errors?: Array<string> | null;
    /**
     * @type {boolean}
     * @memberof DiscoverDaemonsResult
     */
    Success?: boolean;
    /**
     * List of discovered daemon statuses to display in UI
     * @type {Array<DaemonStatusApiModel>}
     * @memberof DiscoverDaemonsResult
     */
    DiscoveredDaemons?: Array<DaemonStatusApiModel> | null;
}
