// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ComponentAuditApiModel,
} from './';

/**
 * @export
 * @interface GetComponentAuditListResponseDto
 */
export interface GetComponentAuditListResponseDto {
    /**
     * @type {number}
     * @memberof GetComponentAuditListResponseDto
     */
    CurrentPage?: number;
    /**
     * @type {number}
     * @memberof GetComponentAuditListResponseDto
     */
    TotalItems?: number;
    /**
     * @type {number}
     * @memberof GetComponentAuditListResponseDto
     */
    TotalPages?: number;
    /**
     * @type {Array<ComponentAuditApiModel>}
     * @memberof GetComponentAuditListResponseDto
     */
    Items?: Array<ComponentAuditApiModel> | null;
}
