// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PropertyFilter, PropertyValue } from './';

/**
 * @export
 * @interface PropertyValueFilter
 */
export interface PropertyValueFilter {
  /**
   * @type {number}
   * @memberof PropertyValueFilter
   */
  Id?: number;
  /**
   * @type {PropertyValue}
   * @memberof PropertyValueFilter
   */
  PropertyValue?: PropertyValue;
  /**
   * @type {PropertyFilter}
   * @memberof PropertyValueFilter
   */
  PropertyFilter?: PropertyFilter;
  /**
   * @type {string}
   * @memberof PropertyValueFilter
   */
  Value?: string | null;
}
