
@echo off
cls
pushd %~dp0
popd
set MYDIR=%CD%
echo Directory of this batch fil: %MYDIR%

call msiexec /i "%MYDIR%\Setup.Dorc.msi" ^
SERVICE.IDENTITY="" ^
SERVICE.PASSWORD="" ^
DEPLOYMENT.DBSERVER=. ^
DEPLOYMENT.DB="" ^
SVC.ACCOUNTPROD="" ^
SVC.PASSWORDPROD=""  ^
SVC.ACCOUNTNONPROD="" ^
SVC.PASSWORDNONPROD="" ^
DB.CONNECTIONSTRING="" ^
SCRIPT.FOLDER="" ^
WEB.BACKGROUND.COLOUR=Grey ^
HA.ENABLED="false" ^
HA.RABBITMQ.HOSTNAME="localhost" ^
HA.RABBITMQ.PORT="5671" ^
HA.RABBITMQ.VIRTUALHOST="/" ^
HA.RABBITMQ.OAUTH.CLIENTID="" ^
HA.RABBITMQ.OAUTH.CLIENTSECRET="" ^
HA.RABBITMQ.OAUTH.TOKENENDPOINT="" ^
HA.RABBITMQ.OAUTH.SCOPE="" ^
HA.RABBITMQ.SSL.ENABLED="true" ^
HA.RABBITMQ.SSL.SERVERNAME="" ^
HA.RABBITMQ.SSL.VERSION="TLS12_TLS13" ^
/qb /L*v "%MYDIR%\Setup.Dorc.log"

echo Returncode: %ERRORLEVEL%
pause