// tslint:disable
/**
 * Build
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  AggregatedResultsByOutcome,
  AggregatedResultsDifference,
  AggregatedRunsByOutcome,
  AggregatedRunsByState,
  TestResultsContext
} from './index';

/**
 *
 * @export
 * @interface AggregatedResultsAnalysis
 */
export interface AggregatedResultsAnalysis {
  /**
   * @type {string}
   * @memberof AggregatedResultsAnalysis
   */
  duration?: string;
  /**
   * @type {{ [key: string]: AggregatedResultsByOutcome; }}
   * @memberof AggregatedResultsAnalysis
   */
  notReportedResultsByOutcome?: { [key: string]: AggregatedResultsByOutcome };
  /**
   * @type {TestResultsContext}
   * @memberof AggregatedResultsAnalysis
   */
  previousContext?: TestResultsContext;
  /**
   * @type {{ [key: string]: AggregatedResultsByOutcome; }}
   * @memberof AggregatedResultsAnalysis
   */
  resultsByOutcome?: { [key: string]: AggregatedResultsByOutcome };
  /**
   * @type {AggregatedResultsDifference}
   * @memberof AggregatedResultsAnalysis
   */
  resultsDifference?: AggregatedResultsDifference;
  /**
   * @type {{ [key: string]: AggregatedRunsByOutcome; }}
   * @memberof AggregatedResultsAnalysis
   */
  runSummaryByOutcome?: { [key: string]: AggregatedRunsByOutcome };
  /**
   * @type {{ [key: string]: AggregatedRunsByState; }}
   * @memberof AggregatedResultsAnalysis
   */
  runSummaryByState?: { [key: string]: AggregatedRunsByState };
  /**
   * @type {number}
   * @memberof AggregatedResultsAnalysis
   */
  totalTests?: number;
}
