// tslint:disable
/**
 * Build
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ReferenceLinks } from './index';

/**
 * Represents an attachment to a build.
 * @export
 * @interface Attachment
 */
export interface Attachment {
  /**
   * @type {ReferenceLinks}
   * @memberof Attachment
   */
  _links?: ReferenceLinks;
  /**
   * The name of the attachment.
   * @type {string}
   * @memberof Attachment
   */
  name?: string;
}
