// tslint:disable
/**
 * Build
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  AgentPoolQueueReference,
  SecureFileReference,
  ServiceEndpointReference,
  VariableGroupReference
} from './index';

/**
 * Represents resources used by a build process.
 * @export
 * @interface BuildProcessResources
 */
export interface BuildProcessResources {
  /**
   * @type {Array<ServiceEndpointReference>}
   * @memberof BuildProcessResources
   */
  endpoints?: Array<ServiceEndpointReference>;
  /**
   * @type {Array<SecureFileReference>}
   * @memberof BuildProcessResources
   */
  files?: Array<SecureFileReference>;
  /**
   * @type {Array<AgentPoolQueueReference>}
   * @memberof BuildProcessResources
   */
  queues?: Array<AgentPoolQueueReference>;
  /**
   * @type {Array<VariableGroupReference>}
   * @memberof BuildProcessResources
   */
  variableGroups?: Array<VariableGroupReference>;
}
