// tslint:disable
/**
 * Build
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the data from the build information nodes for type \"DeploymentInformation\" for xaml builds
 * @export
 * @interface Deployment
 */
export interface Deployment {
  /**
   * @type {string}
   * @memberof Deployment
   */
  type?: string;
}
