// tslint:disable
/**
 * Build
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  BuildDefinitionStep,
  BuildDefinitionVariable,
  Dependency,
  PhaseTarget
} from './index';

/**
 * Represents a phase of a build definition.
 * @export
 * @interface Phase
 */
export interface Phase {
  /**
   * The condition that must be true for this phase to execute.
   * @type {string}
   * @memberof Phase
   */
  condition?: string;
  /**
   * @type {Array<Dependency>}
   * @memberof Phase
   */
  dependencies?: Array<Dependency>;
  /**
   * The job authorization scope for builds queued against this definition.
   * @type {string}
   * @memberof Phase
   */
  jobAuthorizationScope?: PhaseJobAuthorizationScopeEnum;
  /**
   * The cancellation timeout, in minutes, for builds queued against this definition.
   * @type {number}
   * @memberof Phase
   */
  jobCancelTimeoutInMinutes?: number;
  /**
   * The job execution timeout, in minutes, for builds queued against this definition.
   * @type {number}
   * @memberof Phase
   */
  jobTimeoutInMinutes?: number;
  /**
   * The name of the phase.
   * @type {string}
   * @memberof Phase
   */
  name?: string;
  /**
   * The unique ref name of the phase.
   * @type {string}
   * @memberof Phase
   */
  refName?: string;
  /**
   * @type {Array<BuildDefinitionStep>}
   * @memberof Phase
   */
  steps?: Array<BuildDefinitionStep>;
  /**
   * @type {PhaseTarget}
   * @memberof Phase
   */
  target?: PhaseTarget;
  /**
   * @type {{ [key: string]: BuildDefinitionVariable; }}
   * @memberof Phase
   */
  variables?: { [key: string]: BuildDefinitionVariable };
}

/**
 * @export
 * @enum {string}
 */
export enum PhaseJobAuthorizationScopeEnum {
  ProjectCollection = 'projectCollection',
  Project = 'project'
}
