// tslint:disable
/**
 * Build
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a reference to a variable group.
 * @export
 * @interface VariableGroupReference
 */
export interface VariableGroupReference {
  /**
   * The Name of the variable group.
   * @type {string}
   * @memberof VariableGroupReference
   */
  alias?: string;
  /**
   * The ID of the variable group.
   * @type {number}
   * @memberof VariableGroupReference
   */
  id?: number;
}
