// tslint:disable
/**
 * Build
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkspaceMapping } from './index';

/**
 *
 * @export
 * @interface WorkspaceTemplate
 */
export interface WorkspaceTemplate {
  /**
   * Uri of the associated definition
   * @type {string}
   * @memberof WorkspaceTemplate
   */
  definitionUri?: string;
  /**
   * The identity that last modified this template
   * @type {string}
   * @memberof WorkspaceTemplate
   */
  lastModifiedBy?: string;
  /**
   * The last time this template was modified
   * @type {string}
   * @memberof WorkspaceTemplate
   */
  lastModifiedDate?: string;
  /**
   * List of workspace mappings
   * @type {Array<WorkspaceMapping>}
   * @memberof WorkspaceTemplate
   */
  mappings?: Array<WorkspaceMapping>;
  /**
   * Id of the workspace for this template
   * @type {number}
   * @memberof WorkspaceTemplate
   */
  workspaceId?: number;
}
