/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Xunit;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ReportApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReportApiTests : IDisposable
    {
        private ReportApi instance;

        public ReportApiTests()
        {
            instance = new ReportApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReportApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReportApi
            //Assert.IsType<ReportApi>(instance);
        }

        /// <summary>
        /// Test ReportGet
        /// </summary>
        [Fact]
        public void ReportGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string organization = null;
            //string project = null;
            //int buildId = null;
            //string apiVersion = null;
            //string? type = null;
            //var response = instance.ReportGet(organization, project, buildId, apiVersion, type);
            //Assert.IsType<BuildReportMetadata>(response);
        }
    }
}
