/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Xunit;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ResourceUsageApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ResourceUsageApiTests : IDisposable
    {
        private ResourceUsageApi instance;

        public ResourceUsageApiTests()
        {
            instance = new ResourceUsageApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResourceUsageApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ResourceUsageApi
            //Assert.IsType<ResourceUsageApi>(instance);
        }

        /// <summary>
        /// Test ResourceUsageGet
        /// </summary>
        [Fact]
        public void ResourceUsageGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string organization = null;
            //string apiVersion = null;
            //var response = instance.ResourceUsageGet(organization, apiVersion);
            //Assert.IsType<BuildResourceUsage>(response);
        }
    }
}
