/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AgentPoolQueueTarget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentPoolQueueTargetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentPoolQueueTarget
        //private AgentPoolQueueTarget instance;

        public AgentPoolQueueTargetTests()
        {
            // TODO uncomment below to create an instance of AgentPoolQueueTarget
            //instance = new AgentPoolQueueTarget();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentPoolQueueTarget
        /// </summary>
        [Fact]
        public void AgentPoolQueueTargetInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentPoolQueueTarget
            //Assert.IsType<AgentPoolQueueTarget>(instance);
        }


        /// <summary>
        /// Test the property 'AgentSpecification'
        /// </summary>
        [Fact]
        public void AgentSpecificationTest()
        {
            // TODO unit test for the property 'AgentSpecification'
        }
        /// <summary>
        /// Test the property 'AllowScriptsAuthAccessOption'
        /// </summary>
        [Fact]
        public void AllowScriptsAuthAccessOptionTest()
        {
            // TODO unit test for the property 'AllowScriptsAuthAccessOption'
        }
        /// <summary>
        /// Test the property 'Demands'
        /// </summary>
        [Fact]
        public void DemandsTest()
        {
            // TODO unit test for the property 'Demands'
        }
        /// <summary>
        /// Test the property 'ExecutionOptions'
        /// </summary>
        [Fact]
        public void ExecutionOptionsTest()
        {
            // TODO unit test for the property 'ExecutionOptions'
        }
        /// <summary>
        /// Test the property 'Queue'
        /// </summary>
        [Fact]
        public void QueueTest()
        {
            // TODO unit test for the property 'Queue'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
