/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AggregatedResultsDifference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggregatedResultsDifferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AggregatedResultsDifference
        //private AggregatedResultsDifference instance;

        public AggregatedResultsDifferenceTests()
        {
            // TODO uncomment below to create an instance of AggregatedResultsDifference
            //instance = new AggregatedResultsDifference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggregatedResultsDifference
        /// </summary>
        [Fact]
        public void AggregatedResultsDifferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" AggregatedResultsDifference
            //Assert.IsType<AggregatedResultsDifference>(instance);
        }


        /// <summary>
        /// Test the property 'IncreaseInDuration'
        /// </summary>
        [Fact]
        public void IncreaseInDurationTest()
        {
            // TODO unit test for the property 'IncreaseInDuration'
        }
        /// <summary>
        /// Test the property 'IncreaseInFailures'
        /// </summary>
        [Fact]
        public void IncreaseInFailuresTest()
        {
            // TODO unit test for the property 'IncreaseInFailures'
        }
        /// <summary>
        /// Test the property 'IncreaseInNonImpactedTests'
        /// </summary>
        [Fact]
        public void IncreaseInNonImpactedTestsTest()
        {
            // TODO unit test for the property 'IncreaseInNonImpactedTests'
        }
        /// <summary>
        /// Test the property 'IncreaseInOtherTests'
        /// </summary>
        [Fact]
        public void IncreaseInOtherTestsTest()
        {
            // TODO unit test for the property 'IncreaseInOtherTests'
        }
        /// <summary>
        /// Test the property 'IncreaseInPassedTests'
        /// </summary>
        [Fact]
        public void IncreaseInPassedTestsTest()
        {
            // TODO unit test for the property 'IncreaseInPassedTests'
        }
        /// <summary>
        /// Test the property 'IncreaseInTotalTests'
        /// </summary>
        [Fact]
        public void IncreaseInTotalTestsTest()
        {
            // TODO unit test for the property 'IncreaseInTotalTests'
        }

    }

}
