/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BuildUpdatedEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BuildUpdatedEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BuildUpdatedEvent
        //private BuildUpdatedEvent instance;

        public BuildUpdatedEventTests()
        {
            // TODO uncomment below to create an instance of BuildUpdatedEvent
            //instance = new BuildUpdatedEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BuildUpdatedEvent
        /// </summary>
        [Fact]
        public void BuildUpdatedEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" BuildUpdatedEvent
            //Assert.IsType<BuildUpdatedEvent>(instance);
        }


        /// <summary>
        /// Test the property 'Build'
        /// </summary>
        [Fact]
        public void BuildTest()
        {
            // TODO unit test for the property 'Build'
        }
        /// <summary>
        /// Test the property 'BuildId'
        /// </summary>
        [Fact]
        public void BuildIdTest()
        {
            // TODO unit test for the property 'BuildId'
        }

    }

}
