/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BuildTagsAddedEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BuildTagsAddedEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BuildTagsAddedEvent
        //private BuildTagsAddedEvent instance;

        public BuildTagsAddedEventTests()
        {
            // TODO uncomment below to create an instance of BuildTagsAddedEvent
            //instance = new BuildTagsAddedEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BuildTagsAddedEvent
        /// </summary>
        [Fact]
        public void BuildTagsAddedEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" BuildTagsAddedEvent
            //Assert.IsType<BuildTagsAddedEvent>(instance);
        }


        /// <summary>
        /// Test the property 'AllTags'
        /// </summary>
        [Fact]
        public void AllTagsTest()
        {
            // TODO unit test for the property 'AllTags'
        }
        /// <summary>
        /// Test the property 'NewTags'
        /// </summary>
        [Fact]
        public void NewTagsTest()
        {
            // TODO unit test for the property 'NewTags'
        }
        /// <summary>
        /// Test the property 'BuildId'
        /// </summary>
        [Fact]
        public void BuildIdTest()
        {
            // TODO unit test for the property 'BuildId'
        }

    }

}
