/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BuildDefinitionSourceProvider
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BuildDefinitionSourceProviderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BuildDefinitionSourceProvider
        //private BuildDefinitionSourceProvider instance;

        public BuildDefinitionSourceProviderTests()
        {
            // TODO uncomment below to create an instance of BuildDefinitionSourceProvider
            //instance = new BuildDefinitionSourceProvider();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BuildDefinitionSourceProvider
        /// </summary>
        [Fact]
        public void BuildDefinitionSourceProviderInstanceTest()
        {
            // TODO uncomment below to test "IsType" BuildDefinitionSourceProvider
            //Assert.IsType<BuildDefinitionSourceProvider>(instance);
        }


        /// <summary>
        /// Test the property 'DefinitionUri'
        /// </summary>
        [Fact]
        public void DefinitionUriTest()
        {
            // TODO unit test for the property 'DefinitionUri'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Fact]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SupportedTriggerTypes'
        /// </summary>
        [Fact]
        public void SupportedTriggerTypesTest()
        {
            // TODO unit test for the property 'SupportedTriggerTypes'
        }

    }

}
