/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BuildOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BuildOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BuildOption
        //private BuildOption instance;

        public BuildOptionTests()
        {
            // TODO uncomment below to create an instance of BuildOption
            //instance = new BuildOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BuildOption
        /// </summary>
        [Fact]
        public void BuildOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" BuildOption
            //Assert.IsType<BuildOption>(instance);
        }


        /// <summary>
        /// Test the property 'Definition'
        /// </summary>
        [Fact]
        public void DefinitionTest()
        {
            // TODO unit test for the property 'Definition'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Fact]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }

    }

}
