/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Change
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Change
        //private Change instance;

        public ChangeTests()
        {
            // TODO uncomment below to create an instance of Change
            //instance = new Change();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Change
        /// </summary>
        [Fact]
        public void ChangeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Change
            //Assert.IsType<Change>(instance);
        }


        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'DisplayUri'
        /// </summary>
        [Fact]
        public void DisplayUriTest()
        {
            // TODO unit test for the property 'DisplayUri'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'MessageTruncated'
        /// </summary>
        [Fact]
        public void MessageTruncatedTest()
        {
            // TODO unit test for the property 'MessageTruncated'
        }
        /// <summary>
        /// Test the property 'Pusher'
        /// </summary>
        [Fact]
        public void PusherTest()
        {
            // TODO unit test for the property 'Pusher'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
