/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentBuild
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentBuildTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentBuild
        //private DeploymentBuild instance;

        public DeploymentBuildTests()
        {
            // TODO uncomment below to create an instance of DeploymentBuild
            //instance = new DeploymentBuild();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentBuild
        /// </summary>
        [Fact]
        public void DeploymentBuildInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentBuild
            //Assert.IsType<DeploymentBuild>(instance);
        }


        /// <summary>
        /// Test the property 'BuildId'
        /// </summary>
        [Fact]
        public void BuildIdTest()
        {
            // TODO unit test for the property 'BuildId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
