/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Deployment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Deployment
        //private Deployment instance;

        public DeploymentTests()
        {
            // TODO uncomment below to create an instance of Deployment
            //instance = new Deployment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Deployment
        /// </summary>
        [Fact]
        public void DeploymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Deployment
            //Assert.IsType<Deployment>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
