/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JobReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobReference
        //private JobReference instance;

        public JobReferenceTests()
        {
            // TODO uncomment below to create an instance of JobReference
            //instance = new JobReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobReference
        /// </summary>
        [Fact]
        public void JobReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobReference
            //Assert.IsType<JobReference>(instance);
        }


        /// <summary>
        /// Test the property 'Attempt'
        /// </summary>
        [Fact]
        public void AttemptTest()
        {
            // TODO unit test for the property 'Attempt'
        }
        /// <summary>
        /// Test the property 'JobName'
        /// </summary>
        [Fact]
        public void JobNameTest()
        {
            // TODO unit test for the property 'JobName'
        }

    }

}
