/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JustInTimeProcess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JustInTimeProcessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JustInTimeProcess
        //private JustInTimeProcess instance;

        public JustInTimeProcessTests()
        {
            // TODO uncomment below to create an instance of JustInTimeProcess
            //instance = new JustInTimeProcess();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JustInTimeProcess
        /// </summary>
        [Fact]
        public void JustInTimeProcessInstanceTest()
        {
            // TODO uncomment below to test "IsType" JustInTimeProcess
            //Assert.IsType<JustInTimeProcess>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
