/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SourceRepositories
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SourceRepositoriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SourceRepositories
        //private SourceRepositories instance;

        public SourceRepositoriesTests()
        {
            // TODO uncomment below to create an instance of SourceRepositories
            //instance = new SourceRepositories();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SourceRepositories
        /// </summary>
        [Fact]
        public void SourceRepositoriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" SourceRepositories
            //Assert.IsType<SourceRepositories>(instance);
        }


        /// <summary>
        /// Test the property 'ContinuationToken'
        /// </summary>
        [Fact]
        public void ContinuationTokenTest()
        {
            // TODO unit test for the property 'ContinuationToken'
        }
        /// <summary>
        /// Test the property 'PageLength'
        /// </summary>
        [Fact]
        public void PageLengthTest()
        {
            // TODO unit test for the property 'PageLength'
        }
        /// <summary>
        /// Test the property 'Repositories'
        /// </summary>
        [Fact]
        public void RepositoriesTest()
        {
            // TODO unit test for the property 'Repositories'
        }
        /// <summary>
        /// Test the property 'TotalPageCount'
        /// </summary>
        [Fact]
        public void TotalPageCountTest()
        {
            // TODO unit test for the property 'TotalPageCount'
        }

    }

}
