/*
 * Build
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0
 * Contact: nugetvss@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SourceProviderAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SourceProviderAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SourceProviderAttributes
        //private SourceProviderAttributes instance;

        public SourceProviderAttributesTests()
        {
            // TODO uncomment below to create an instance of SourceProviderAttributes
            //instance = new SourceProviderAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SourceProviderAttributes
        /// </summary>
        [Fact]
        public void SourceProviderAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" SourceProviderAttributes
            //Assert.IsType<SourceProviderAttributes>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SupportedCapabilities'
        /// </summary>
        [Fact]
        public void SupportedCapabilitiesTest()
        {
            // TODO unit test for the property 'SupportedCapabilities'
        }
        /// <summary>
        /// Test the property 'SupportedTriggers'
        /// </summary>
        [Fact]
        public void SupportedTriggersTest()
        {
            // TODO unit test for the property 'SupportedTriggers'
        }

    }

}
