// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    AnalyticsMonthlyOutcomeApiModel,
} from '../models';

/**
 * no description
 */
export class AnalyticsMonthlyOutcomeApi extends BaseAPI {

    /**
     */
    analyticsMonthlyOutcomeGet(): Observable<Array<AnalyticsMonthlyOutcomeApiModel>>
    analyticsMonthlyOutcomeGet(opts?: OperationOpts): Observable<AjaxResponse<Array<AnalyticsMonthlyOutcomeApiModel>>>
    analyticsMonthlyOutcomeGet(opts?: OperationOpts): Observable<Array<AnalyticsMonthlyOutcomeApiModel> | AjaxResponse<Array<AnalyticsMonthlyOutcomeApiModel>>> {
        return this.request<Array<AnalyticsMonthlyOutcomeApiModel>>({
            url: '/AnalyticsMonthlyOutcome',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
