// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    AnalyticsComponentUsageApiModel,
} from '../models';

/**
 * no description
 */
export class AnalyticsComponentUsageApi extends BaseAPI {

    /**
     */
    analyticsComponentUsageGet(): Observable<Array<AnalyticsComponentUsageApiModel>>
    analyticsComponentUsageGet(opts?: OperationOpts): Observable<AjaxResponse<Array<AnalyticsComponentUsageApiModel>>>
    analyticsComponentUsageGet(opts?: OperationOpts): Observable<Array<AnalyticsComponentUsageApiModel> | AjaxResponse<Array<AnalyticsComponentUsageApiModel>>> {
        return this.request<Array<AnalyticsComponentUsageApiModel>>({
            url: '/AnalyticsComponentUsage',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
