// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    CopyEnvBuildDto,
    CopyEnvBuildResponseDto,
} from '../models';

export interface CopyEnvBuildPostRequest {
    copyEnvBuildDto?: CopyEnvBuildDto;
}

/**
 * no description
 */
export class CopyEnvBuildApi extends BaseAPI {

    /**
     */
    copyEnvBuildPost({ copyEnvBuildDto }: CopyEnvBuildPostRequest): Observable<CopyEnvBuildResponseDto>
    copyEnvBuildPost({ copyEnvBuildDto }: CopyEnvBuildPostRequest, opts?: OperationOpts): Observable<AjaxResponse<CopyEnvBuildResponseDto>>
    copyEnvBuildPost({ copyEnvBuildDto }: CopyEnvBuildPostRequest, opts?: OperationOpts): Observable<CopyEnvBuildResponseDto | AjaxResponse<CopyEnvBuildResponseDto>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            // oauth required
            ...(this.configuration.accessToken != null
                ? { Authorization: typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('oauth2', ['dorc-api-np.manage'])
                    : this.configuration.accessToken }
                : undefined
            ),
        };

        return this.request<CopyEnvBuildResponseDto>({
            url: '/CopyEnvBuild',
            method: 'POST',
            headers,
            body: copyEnvBuildDto,
        }, opts?.responseOpts);
    };

}
