// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';

/**
 * no description
 */
export class MetadataApi extends BaseAPI {

    /**
     */
    metadataGet(): Observable<string>
    metadataGet(opts?: OperationOpts): Observable<AjaxResponse<string>>
    metadataGet(opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken != null
                ? { Authorization: typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('oauth2', ['dorc-api-np.manage'])
                    : this.configuration.accessToken }
                : undefined
            ),
        };

        return this.request<string>({
            url: '/Metadata',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    metadataIsProductionGet(): Observable<boolean>
    metadataIsProductionGet(opts?: OperationOpts): Observable<AjaxResponse<boolean>>
    metadataIsProductionGet(opts?: OperationOpts): Observable<boolean | AjaxResponse<boolean>> {
        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken != null
                ? { Authorization: typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('oauth2', ['dorc-api-np.manage'])
                    : this.configuration.accessToken }
                : undefined
            ),
        };

        return this.request<boolean>({
            url: '/Metadata/IsProduction',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
