// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
  GetPropertyValuesAuditListResponseDto,
  PagedDataOperators
} from '../models';

export interface PropertyValuesAuditPutRequest {
  page?: number;
  limit?: number;
  pagedDataOperators?: PagedDataOperators;
}

/**
 * no description
 */
export class PropertyValuesAuditApi extends BaseAPI {
  /**
   */
  propertyValuesAuditPut({
    page,
    limit,
    pagedDataOperators
  }: PropertyValuesAuditPutRequest): Observable<GetPropertyValuesAuditListResponseDto>;
  propertyValuesAuditPut(
    { page, limit, pagedDataOperators }: PropertyValuesAuditPutRequest,
    opts?: OperationOpts
  ): Observable<AjaxResponse<GetPropertyValuesAuditListResponseDto>>;
  propertyValuesAuditPut(
    { page, limit, pagedDataOperators }: PropertyValuesAuditPutRequest,
    opts?: OperationOpts
  ): Observable<
    | GetPropertyValuesAuditListResponseDto
    | AjaxResponse<GetPropertyValuesAuditListResponseDto>
  > {
    const headers: HttpHeaders = {
      'Content-Type': 'application/json'
    };

    const query: HttpQuery = {};

    if (page != null) {
      query['page'] = page;
    }
    if (limit != null) {
      query['limit'] = limit;
    }

    return this.request<GetPropertyValuesAuditListResponseDto>(
      {
        url: '/PropertyValuesAudit',
        method: 'PUT',
        headers,
        query,
        body: pagedDataOperators
      },
      opts?.responseOpts
    );
  }
}
