// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    PermissionDto,
    SqlPortApiModel,
} from '../models';

export interface RefDataSqlPortsDeleteRequest {
    id?: number;
}

export interface RefDataSqlPortsPostRequest {
    permissionDto?: PermissionDto;
}

export interface RefDataSqlPortsPutRequest {
    id?: number;
    permissionDto?: PermissionDto;
}

/**
 * no description
 */
export class RefDataSqlPortsApi extends BaseAPI {

    /**
     */
    refDataSqlPortsDelete({ id }: RefDataSqlPortsDeleteRequest): Observable<void>
    refDataSqlPortsDelete({ id }: RefDataSqlPortsDeleteRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    refDataSqlPortsDelete({ id }: RefDataSqlPortsDeleteRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {

        const query: HttpQuery = {};

        if (id != null) { query['id'] = id; }

        return this.request<void>({
            url: '/RefDataSqlPorts',
            method: 'DELETE',
            query,
        }, opts?.responseOpts);
    };

    /**
     */
    refDataSqlPortsGet(): Observable<Array<SqlPortApiModel>>
    refDataSqlPortsGet(opts?: OperationOpts): Observable<AjaxResponse<Array<SqlPortApiModel>>>
    refDataSqlPortsGet(opts?: OperationOpts): Observable<Array<SqlPortApiModel> | AjaxResponse<Array<SqlPortApiModel>>> {
        return this.request<Array<SqlPortApiModel>>({
            url: '/RefDataSqlPorts',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    refDataSqlPortsPost({ permissionDto }: RefDataSqlPortsPostRequest): Observable<void>
    refDataSqlPortsPost({ permissionDto }: RefDataSqlPortsPostRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    refDataSqlPortsPost({ permissionDto }: RefDataSqlPortsPostRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/RefDataSqlPorts',
            method: 'POST',
            headers,
            body: permissionDto,
        }, opts?.responseOpts);
    };

    /**
     */
    refDataSqlPortsPut({ id, permissionDto }: RefDataSqlPortsPutRequest): Observable<void>
    refDataSqlPortsPut({ id, permissionDto }: RefDataSqlPortsPutRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    refDataSqlPortsPut({ id, permissionDto }: RefDataSqlPortsPutRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        const query: HttpQuery = {};

        if (id != null) { query['id'] = id; }

        return this.request<void>({
            url: '/RefDataSqlPorts',
            method: 'PUT',
            headers,
            query,
            body: permissionDto,
        }, opts?.responseOpts);
    };

}
