// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    UserApiModel,
} from '../models';

export interface RefDataDatabaseUsersGetRequest {
    id?: number;
    envId?: number;
}

/**
 * no description
 */
export class RefDataDatabaseUsersApi extends BaseAPI {

    /**
     */
    refDataDatabaseUsersGet({ id, envId }: RefDataDatabaseUsersGetRequest): Observable<Array<UserApiModel>>
    refDataDatabaseUsersGet({ id, envId }: RefDataDatabaseUsersGetRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<UserApiModel>>>
    refDataDatabaseUsersGet({ id, envId }: RefDataDatabaseUsersGetRequest, opts?: OperationOpts): Observable<Array<UserApiModel> | AjaxResponse<Array<UserApiModel>>> {

        const query: HttpQuery = {};

        if (id != null) { query['id'] = id; }
        if (envId != null) { query['envId'] = envId; }

        return this.request<Array<UserApiModel>>({
            url: '/RefDataDatabaseUsers',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

}
