// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    ApiApiModel,
    ApiBoolResult,
} from '../models';

export interface RefDataApisDeleteRequest {
    id?: number;
}

export interface RefDataApisForEnvironmentEnvironmentIdGetRequest {
    environmentId: number;
}

export interface RefDataApisIdGetRequest {
    id: number;
}

export interface RefDataApisPostRequest {
    environmentId?: number;
    apiApiModel?: ApiApiModel;
}

export interface RefDataApisPutRequest {
    apiApiModel?: ApiApiModel;
}

/**
 * no description
 */
export class RefDataApisApi extends BaseAPI {

    /**
     */
    refDataApisDelete({ id }: RefDataApisDeleteRequest): Observable<ApiBoolResult>
    refDataApisDelete({ id }: RefDataApisDeleteRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiBoolResult>>
    refDataApisDelete({ id }: RefDataApisDeleteRequest, opts?: OperationOpts): Observable<ApiBoolResult | AjaxResponse<ApiBoolResult>> {

        const query: HttpQuery = {};

        if (id != null) { query['id'] = id; }

        return this.request<ApiBoolResult>({
            url: '/RefDataApis',
            method: 'DELETE',
            query,
        }, opts?.responseOpts);
    };

    /**
     */
    refDataApisForEnvironmentEnvironmentIdGet({ environmentId }: RefDataApisForEnvironmentEnvironmentIdGetRequest): Observable<Array<ApiApiModel>>
    refDataApisForEnvironmentEnvironmentIdGet({ environmentId }: RefDataApisForEnvironmentEnvironmentIdGetRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<ApiApiModel>>>
    refDataApisForEnvironmentEnvironmentIdGet({ environmentId }: RefDataApisForEnvironmentEnvironmentIdGetRequest, opts?: OperationOpts): Observable<Array<ApiApiModel> | AjaxResponse<Array<ApiApiModel>>> {
        throwIfNullOrUndefined(environmentId, 'environmentId', 'refDataApisForEnvironmentEnvironmentIdGet');

        return this.request<Array<ApiApiModel>>({
            url: '/RefDataApis/ForEnvironment/{environmentId}'.replace('{environmentId}', encodeURI(environmentId)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    refDataApisIdGet({ id }: RefDataApisIdGetRequest): Observable<ApiApiModel>
    refDataApisIdGet({ id }: RefDataApisIdGetRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiApiModel>>
    refDataApisIdGet({ id }: RefDataApisIdGetRequest, opts?: OperationOpts): Observable<ApiApiModel | AjaxResponse<ApiApiModel>> {
        throwIfNullOrUndefined(id, 'id', 'refDataApisIdGet');

        return this.request<ApiApiModel>({
            url: '/RefDataApis/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    refDataApisPost({ environmentId, apiApiModel }: RefDataApisPostRequest): Observable<ApiApiModel>
    refDataApisPost({ environmentId, apiApiModel }: RefDataApisPostRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiApiModel>>
    refDataApisPost({ environmentId, apiApiModel }: RefDataApisPostRequest, opts?: OperationOpts): Observable<ApiApiModel | AjaxResponse<ApiApiModel>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        const query: HttpQuery = {};

        if (environmentId != null) { query['environmentId'] = environmentId; }

        return this.request<ApiApiModel>({
            url: '/RefDataApis',
            method: 'POST',
            headers,
            query,
            body: apiApiModel,
        }, opts?.responseOpts);
    };

    /**
     */
    refDataApisPut({ apiApiModel }: RefDataApisPutRequest): Observable<ApiApiModel>
    refDataApisPut({ apiApiModel }: RefDataApisPutRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiApiModel>>
    refDataApisPut({ apiApiModel }: RefDataApisPutRequest, opts?: OperationOpts): Observable<ApiApiModel | AjaxResponse<ApiApiModel>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ApiApiModel>({
            url: '/RefDataApis',
            method: 'PUT',
            headers,
            body: apiApiModel,
        }, opts?.responseOpts);
    };

}
