// tslint:disable
/**
 * Dorc.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    ComponentApiModel,
    TerraformPlanApiModel,
    TerraformTemplateManifest,
    TerraformTemplateInstantiateRequestApiModel,
} from '../models';

export interface TerraformTemplateInstantiateRequest {
    name: string;
    version: string;
    body: TerraformTemplateInstantiateRequestApiModel;
}

export interface TerraformTemplateGetByNameRequest {
    name: string;
}

export interface TerraformTemplateGetByNameVersionRequest {
    name: string;
    version: string;
}

export interface TerraformPlanDeploymentResultIdConfirmPostRequest {
    deploymentResultId: number;
}

export interface TerraformPlanDeploymentResultIdDeclinePostRequest {
    deploymentResultId: number;
}

export interface TerraformPlanDeploymentResultIdGetRequest {
    deploymentResultId: number;
}

/**
 * no description
 */
export class TerraformApi extends BaseAPI {

    /**
     */
    terraformPlanDeploymentResultIdConfirmPost({ deploymentResultId }: TerraformPlanDeploymentResultIdConfirmPostRequest): Observable<void>
    terraformPlanDeploymentResultIdConfirmPost({ deploymentResultId }: TerraformPlanDeploymentResultIdConfirmPostRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    terraformPlanDeploymentResultIdConfirmPost({ deploymentResultId }: TerraformPlanDeploymentResultIdConfirmPostRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(deploymentResultId, 'deploymentResultId', 'terraformPlanDeploymentResultIdConfirmPost');

        return this.request<void>({
            url: '/Terraform/plan/{deploymentResultId}/confirm'.replace('{deploymentResultId}', encodeURI(deploymentResultId)),
            method: 'POST',
        }, opts?.responseOpts);
    };

    /**
     */
    terraformPlanDeploymentResultIdDeclinePost({ deploymentResultId }: TerraformPlanDeploymentResultIdDeclinePostRequest): Observable<void>
    terraformPlanDeploymentResultIdDeclinePost({ deploymentResultId }: TerraformPlanDeploymentResultIdDeclinePostRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    terraformPlanDeploymentResultIdDeclinePost({ deploymentResultId }: TerraformPlanDeploymentResultIdDeclinePostRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(deploymentResultId, 'deploymentResultId', 'terraformPlanDeploymentResultIdDeclinePost');

        return this.request<void>({
            url: '/Terraform/plan/{deploymentResultId}/decline'.replace('{deploymentResultId}', encodeURI(deploymentResultId)),
            method: 'POST',
        }, opts?.responseOpts);
    };

    /**
     */
    terraformPlanDeploymentResultIdGet({ deploymentResultId }: TerraformPlanDeploymentResultIdGetRequest): Observable<TerraformPlanApiModel>
    terraformPlanDeploymentResultIdGet({ deploymentResultId }: TerraformPlanDeploymentResultIdGetRequest, opts?: OperationOpts): Observable<AjaxResponse<TerraformPlanApiModel>>
    terraformPlanDeploymentResultIdGet({ deploymentResultId }: TerraformPlanDeploymentResultIdGetRequest, opts?: OperationOpts): Observable<TerraformPlanApiModel | AjaxResponse<TerraformPlanApiModel>> {
        throwIfNullOrUndefined(deploymentResultId, 'deploymentResultId', 'terraformPlanDeploymentResultIdGet');

        return this.request<TerraformPlanApiModel>({
            url: '/Terraform/plan/{deploymentResultId}'.replace('{deploymentResultId}', encodeURI(deploymentResultId)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Lists every stock Terraform template available in the DOrc catalog.
     */
    terraformTemplatesGet(): Observable<TerraformTemplateManifest[]>
    terraformTemplatesGet(opts?: OperationOpts): Observable<AjaxResponse<TerraformTemplateManifest[]>>
    terraformTemplatesGet(opts?: OperationOpts): Observable<TerraformTemplateManifest[] | AjaxResponse<TerraformTemplateManifest[]>> {
        return this.request<TerraformTemplateManifest[]>({
            url: '/Terraform/templates',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Latest version of a named stock template.
     */
    terraformTemplateLatestGet({ name }: TerraformTemplateGetByNameRequest): Observable<TerraformTemplateManifest>
    terraformTemplateLatestGet({ name }: TerraformTemplateGetByNameRequest, opts?: OperationOpts): Observable<AjaxResponse<TerraformTemplateManifest>>
    terraformTemplateLatestGet({ name }: TerraformTemplateGetByNameRequest, opts?: OperationOpts): Observable<TerraformTemplateManifest | AjaxResponse<TerraformTemplateManifest>> {
        throwIfNullOrUndefined(name, 'name', 'terraformTemplateLatestGet');
        return this.request<TerraformTemplateManifest>({
            url: '/Terraform/templates/{name}'.replace('{name}', encodeURI(name)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Specific (name, version) of a stock template.
     */
    terraformTemplateVersionGet({ name, version }: TerraformTemplateGetByNameVersionRequest): Observable<TerraformTemplateManifest>
    terraformTemplateVersionGet({ name, version }: TerraformTemplateGetByNameVersionRequest, opts?: OperationOpts): Observable<AjaxResponse<TerraformTemplateManifest>>
    terraformTemplateVersionGet({ name, version }: TerraformTemplateGetByNameVersionRequest, opts?: OperationOpts): Observable<TerraformTemplateManifest | AjaxResponse<TerraformTemplateManifest>> {
        throwIfNullOrUndefined(name, 'name', 'terraformTemplateVersionGet');
        throwIfNullOrUndefined(version, 'version', 'terraformTemplateVersionGet');
        return this.request<TerraformTemplateManifest>({
            url: '/Terraform/templates/{name}/{version}'
                .replace('{name}', encodeURI(name))
                .replace('{version}', encodeURI(version)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Instantiate a stock template as a new Catalog-mode component in the
     * destination project. Does not trigger a deployment - the engineer
     * deploys the resulting component via the existing DOrc deploy flow.
     */
    terraformTemplateInstantiatePost({ name, version, body }: TerraformTemplateInstantiateRequest): Observable<ComponentApiModel>
    terraformTemplateInstantiatePost({ name, version, body }: TerraformTemplateInstantiateRequest, opts?: OperationOpts): Observable<AjaxResponse<ComponentApiModel>>
    terraformTemplateInstantiatePost({ name, version, body }: TerraformTemplateInstantiateRequest, opts?: OperationOpts): Observable<ComponentApiModel | AjaxResponse<ComponentApiModel>> {
        throwIfNullOrUndefined(name, 'name', 'terraformTemplateInstantiatePost');
        throwIfNullOrUndefined(version, 'version', 'terraformTemplateInstantiatePost');
        throwIfNullOrUndefined(body, 'body', 'terraformTemplateInstantiatePost');
        return this.request<ComponentApiModel>({
            url: '/Terraform/templates/{name}/{version}/instantiate'
                .replace('{name}', encodeURI(name))
                .replace('{version}', encodeURI(version)),
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body,
        }, opts?.responseOpts);
    };

}
