using System.Text;

namespace Dorc.TerraformRunner.State
{
    // Owns the rendering of the platform-managed Terraform backend
    // declaration into the working directory before `terraform init`.
    //
    // Per HLPS SC-01: the file name is fixed, the contents are deterministic
    // for a given (storage account, container, state key) triple, and the
    // file is the only backend declaration permitted in the working tree
    // (see TerraformBackendValidator).
    public static class TerraformBackendRenderer
    {
        public const string BackendFileName = "_dorc_backend.tf";

        public sealed record AzureBlobBackend(
            string StorageAccount,
            string ContainerName,
            string Key,
            string? ResourceGroup);

        public static string RenderAzureBlob(AzureBlobBackend backend)
        {
            if (string.IsNullOrEmpty(backend.StorageAccount)) throw new ArgumentException("StorageAccount required", nameof(backend));
            if (string.IsNullOrEmpty(backend.ContainerName)) throw new ArgumentException("ContainerName required", nameof(backend));
            if (string.IsNullOrEmpty(backend.Key)) throw new ArgumentException("Key required", nameof(backend));

            var sb = new StringBuilder();
            sb.AppendLine("# Generated by DOrc - DO NOT EDIT.");
            sb.AppendLine("# State is platform-managed; see docs/Terraform/STATE-MODEL.md.");
            sb.AppendLine("terraform {");
            sb.AppendLine("  backend \"azurerm\" {");
            if (!string.IsNullOrEmpty(backend.ResourceGroup))
            {
                sb.AppendLine($"    resource_group_name  = \"{Escape(backend.ResourceGroup)}\"");
            }
            sb.AppendLine($"    storage_account_name = \"{Escape(backend.StorageAccount)}\"");
            sb.AppendLine($"    container_name       = \"{Escape(backend.ContainerName)}\"");
            sb.AppendLine($"    key                  = \"{Escape(backend.Key)}\"");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static void WriteToWorkingDirectory(string workingDirectory, AzureBlobBackend backend)
        {
            if (string.IsNullOrEmpty(workingDirectory)) throw new ArgumentException("workingDirectory required", nameof(workingDirectory));
            // Reject parent-directory segments before any disk write; the
            // backend file must land inside the explicit working dir, never
            // somewhere reachable via '../'.
            if (workingDirectory.Contains(".."))
            {
                throw new ArgumentException("workingDirectory must not contain parent-directory segments", nameof(workingDirectory));
            }
            Directory.CreateDirectory(workingDirectory);
            var path = Path.Join(workingDirectory, BackendFileName);
            File.WriteAllText(path, RenderAzureBlob(backend));
        }

        private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
