/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { DeploymentEventData } from '../Dorc.Core.Events';

export type IDeploymentsEventsClient = {
    /**
    * @param data Transpiled from Dorc.Core.Events.DeploymentEventData
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    onDeploymentRequestStatusChanged(data: DeploymentEventData): Promise<void>;
    /**
    * @param data Transpiled from Dorc.Core.Events.DeploymentEventData
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    onDeploymentRequestStarted(data: DeploymentEventData): Promise<void>;
    /**
    * @param data Transpiled from Dorc.Core.Events.DeploymentEventData
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    onDeploymentResultStatusChanged(data: DeploymentEventData): Promise<void>;
}

